"""match_added_without_fk_chat

Revision ID: 1fe590117cab
Revises: dfbda5f5e16c
Create Date: 2026-01-15 10:55:53.019392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe590117cab'
down_revision: Union[str, Sequence[str], None] = 'dfbda5f5e16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=True),
    sa.Column('is_match', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_swipe_target_id', 'matches', ['target_id'], unique=False)
    op.create_index('idx_swipe_user_id', 'matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_swipe_user_id', table_name='matches')
    op.drop_index('idx_swipe_target_id', table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
