"""add_location_name_to_profile

Revision ID: 564914fa2257
Revises: e5508f51c61e
Create Date: 2026-01-16 10:48:31.509550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564914fa2257'
down_revision: Union[str, Sequence[str], None] = 'e5508f51c61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('location_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'location_name')
    # ### end Alembic commands ###
