"""add image to events

Revision ID: 77c8f8d373b8
Revises: 3a2a0500089f
Create Date: 2026-01-16 19:02:51.454789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c8f8d373b8'
down_revision: Union[str, Sequence[str], None] = '3a2a0500089f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_file_name', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_goals_name_unique'), table_name='goals', if_exists=True)
    op.execute("UPDATE events SET image_file_name = 'default_event_image.svg' WHERE image_file_name IS NULL")
    op.alter_column('events', 'image_file_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_goals_name_unique'), 'goals', ['name'], unique=True)
    op.drop_column('events', 'image_file_name')
    # ### end Alembic commands ###
