"""fix_matches_fk_and_notification_enum

Revision ID: 78c722921263
Revises: 6b07a82adc84
Create Date: 2026-01-15 21:12:22.813622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '78c722921263'
down_revision: Union[str, Sequence[str], None] = '6b07a82adc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='notificationtype',
        new_values=['NEW_MATCH', 'MATCH_CONFIRMED', 'MATCH_DECLINED', 'EVENT_STATUS_CHANGED', 'EVENT_UPDATED', 'EVENT_CANCELLED', 'EVENT_REMINDER', 'NEW_PARTICIPANT', 'PARTICIPANT_LEFT', 'SYSTEM_MESSAGE'],
        affected_columns=[TableReference(table_schema='public', table_name='notifications', column_name='type')],
        enum_values_to_rename=[],
    )
    op.create_foreign_key(None, 'matches', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='notificationtype',
        new_values=['NEW_MATCH', 'MATCH_CONFIRMED', 'MATCH_DECLINED', 'EVENT_STATUS_CHANGED', 'EVENT_UPDATED', 'EVENT_CANCELLED', 'EVENT_REMINDER', 'NEW_PARTICIPANT', 'PARTICIPANT_LEFT', 'NEW_REVIEW', 'SYSTEM_MESSAGE'],
        affected_columns=[TableReference(table_schema='public', table_name='notifications', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
