"""birthdate_to_profile

Revision ID: b1bec49399f8
Revises: d8dc0f26fda9
Create Date: 2026-01-14 22:38:50.046069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1bec49399f8'
down_revision: Union[str, Sequence[str], None] = 'd8dc0f26fda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('birthdate', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'birthdate')
    # ### end Alembic commands ###
