"""add chat_id in event

Revision ID: c3dd0eb97e4a
Revises: aaeec9ded446
Create Date: 2026-01-15 11:49:01.284354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3dd0eb97e4a'
down_revision: Union[str, Sequence[str], None] = 'aaeec9ded446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('chat_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'events', 'chats', ['chat_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'chat_id')
    # ### end Alembic commands ###
