"""add messenger tables

Revision ID: e40e0e7e2820
Revises: b1bec49399f8
Create Date: 2026-01-15 08:50:07.337618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40e0e7e2820'
down_revision: Union[str, Sequence[str], None] = 'b1bec49399f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('direct', 'channel', 'group', name='chat_type', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('image_file_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_type'), 'chats', ['type'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index('ix_messages_chat_sent_at', 'messages', ['chat_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('chat_participations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.Column('last_read_at', sa.String(length=36), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_at'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'user_id', name='uq_chat_user')
    )
    op.create_index(op.f('ix_chat_participations_chat_id'), 'chat_participations', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_participations_last_read_at'), 'chat_participations', ['last_read_at'], unique=False)
    op.create_index(op.f('ix_chat_participations_user_id'), 'chat_participations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_participations_user_id'), table_name='chat_participations')
    op.drop_index(op.f('ix_chat_participations_last_read_at'), table_name='chat_participations')
    op.drop_index(op.f('ix_chat_participations_chat_id'), table_name='chat_participations')
    op.drop_table('chat_participations')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index('ix_messages_chat_sent_at', table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chats_type'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
